config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'rooms#index'


  get "/posts" => "posts#index"


  concern :voteable do
    post '/votes(.:format)', to: 'votes#vote'
    #resources :votes
  end

  resources :users

  resources :rooms, shallow: true  do
    resources :posts, concerns: :voteable do
      resources :comments
    end
  end

  # if no route matches
  match ":url", to: redirect('/404'), via: :all

end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many      :posts
  has_many      :moderators
  belongs_to    :user

  validates_presence_of :name, :description

  after_create do
    Moderator.create!(
      user_id: self.user_id,
      room_id: self.id
    )
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  after_action :verify_authorized

  def index
    @rooms = Room.order(:name).page params[:page]
    skip_authorization
  end

  def show
    @room = Room.find(params[:id])
    @posts = @room.posts.order(:created_at).reverse_order
    @votes = {}
    current_user.votes.map { |o| @votes[o.post_id] = o.value }
    authorize @room
  end

  def new
    @room = Room.new
    authorize @room
  end

  def edit
    @room = Room.find(params[:id])
    authorize @room
  end

  def create
    @room = Room.new(
      approved_params.merge({ user_id: current_user.id})
    )
    authorize @room
    if @room.save
      flash[:success] = "Room successfully created."
      redirect_to room_path(@room.id)
    else
      flash.now[:warning] =  @room.errors.full_messages
      render :new
    end
  end

  def update
    @room = Room.find(params[:id])
    authorize @room

    @room.update(approved_params)

    if @room.save
      flash[:success] = "Room successfully updated."
      redirect_to rooms_path
    else
      flash.now[:warning] =  @room.errors.full_messages
      render :new
    end
  end

  def destroy
    @room = Room.find(params[:id])
    authorize @room
    if @room.destroy
      flash[:success] = "#{@room.name} is no longer..."
    else
      handle_soft_error @room.errors.full_messages
    end

    redirect_to rooms_path

  end

  def approved_params
    params.require(:room).permit(
      :name,
      :description
    )
  end

end

app/views/rooms/_form.html.erb
<%= bootstrap_form_for @room do |f|%>

    <%= f.text_field        :name %>
    <%= f.text_area         :description %>

    <button class="btn btn-primary">Submit</button>

<% end %>

app/views/rooms/edit.html.erb
<h1>Edit Room</h1>
<%= link_to "Delete Room", room_path, class: "btn btn-default", method: :delete %>

<%= render "shared/flash" %>

<%= render "form" %>

app/views/rooms/index.html.erb
<table class="table table-hover">
<tr>
  <td>name</td>
  <td>description</td>
  <td>started</td>
</tr>

<p class="text-left">
  <% if current_user %>
  <%= link_to "Create Room", new_room_path, class: "btn btn-default" %>
  <% end %>
</p>

<%= render "shared/flash" %>

<% @rooms.each do |room| %>
<tr>
  <td><%= link_to room.name, room %></td>
  <td><%= room.description %></td>
    <td><%= room.created_at.to_date %></td>
</tr>
<% end %>

</table>

<%= paginate @rooms %>

app/views/rooms/new.html.erb
<h1>Create Room</h1>

<%= render "shared/flash" %>

<%= render "form" %>

app/views/rooms/show.html.erb
<%= provide(:page_header, @room.name) %>
<%= provide(:subtext, @room.description) %>

<p class="text-left">
  <%= link_to "New Post", new_room_post_path(:room_id => @room.id), class: "btn btn-default" %>


  <% if policy(@room).is_owner? %>
  <%= link_to "Edit Room", edit_room_path, class: "btn btn-default" %>
  <%= link_to "Delete Room", room_path(@room), method: :delete, class: "btn btn-default" %>
  <% end %>

</p>

<%= render "shared/flash" %>

<table class="table table-hover" id="posts-table">
  <tr>
    <th>Score</th>
    <th>Vote</th>
    <th>Post</th>
    <th>User</th>
    <th>Added</th>
    <th>Total Messages</th>
  </tr>

  <% @posts.each do |post| %>
  <tr>
    <td><%= post.sum %></td>
    <td>
      <% current_vote = @votes[post.id] %>
      <div
         class="vote-box"
         data-post-value="<%= post.id %>"
         data-static-vote-value="<%= @votes[post.id] ? current_vote : 0 %>"
         >
        <a href="#" data-vote-value="1" class="btn btn-default fa fa-thumbs-o-up fa-lg btn-upvote"></a>
        <a href="#" data-vote-value="-1" class="btn btn-default fa fa-thumbs-o-down fa-lg btn-downvote"></a>
      </div>
    </td>
    <td><%= link_to post.title, post_path(post) %></td>
    <td><%= link_to post.user.username, user_path(post.user) %></td>
    <td><%= post.created_at %></td>
    <td><%= post.comments.count %></td>
  </tr>
  <% end %>

</table>