config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'rooms#index'


  get "/posts" => "posts#index"


  concern :voteable do
    post '/votes(.:format)', to: 'votes#vote'
    #resources :votes
  end

  resources :users

  resources :rooms, shallow: true  do
    resources :posts, concerns: :voteable do
      resources :comments
    end
  end

  # if no route matches
  match ":url", to: redirect('/404'), via: :all

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :room
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :votes

  validates :content, presence: true
  validates :title, presence: true

  def sum
    self.votes.sum("value")
  end

  def all_comments
    subtree = self.class.all_comments_sql(self)
    results = ActiveRecord::Base.connection.execute( subtree )
    results = results.to_a.map { |h| h.values.first.to_i }
    Comment.find( results ).index_by( &:id ).slice( *results ).values
  end

  def self.all_comments_sql(instance)
    records_array = <<-SQL
WITH RECURSIVE comment_tree(id, content, commentable_id, commentable_type, path) AS (
  SELECT id, content, commentable_id, commentable_type, ARRAY[id]
  FROM comments
  WHERE commentable_type = 'Post' AND commentable_id = '#{instance.id}'
UNION ALL
  SELECT comments.id, comments.content, comments.commentable_id, comments.commentable_type, path || comments.id
  FROM comment_tree
  JOIN comments ON comments.commentable_id=comment_tree.id
  WHERE NOT comments.id = ANY(path) AND comments.commentable_type = 'Comment'
)
SELECT id
FROM comment_tree
ORDER BY path
  SQL
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_room, only: [:new, :create]
  after_action :verify_authorized

  def index
    @posts = Post.order(:updated_at).page params[:page]
    authorize @posts
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.all_comments
    authorize @post
  end

  def new
    @post = @room.posts.new(user_id: current_user.id)
    authorize @post
  end

  def edit
    @post = Post.find(params[:id])
    authorize @post
  end

  def create
    @post = @room.posts.new( approved_params.merge(user_id: current_user.id) )
    authorize @post

    if @post.save
      flash[:success] = "successful post"
      redirect_to @room
    else
      flash.now[:warning] =  @post.errors.full_messages
      render :new
    end

  end

  def update
    @post = Post.find(params[:id])
    authorize @post
    @post.update(approved_params)

    if @post.save
      flash[:success] = "successfully updated."
      redirect_to room_path(@post.room)
    else
      flash.now[:warning] =  @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    authorize @post

    if @post.destroy
      flash[:success] = "Post successfully deleted."
    else
      handle_soft_error @post.errors.full_messages
    end

    redirect_to room_path(params[:room_id])
  end

  private

  def set_room
    @room = Room.find(params[:room_id])
  end

  def approved_params
    params.require(:post).permit(
      :title,
      :content,
    )
  end

end

app/views/posts/_form.html.erb
<%= form_tag(room_posts_path, method: "post") do %>

<div class="form-group">
  <%= label_tag(:title, "Title") %><br>
  <%= text_field_tag(:title, @post.title, class: 'form-control') %><br>
</div>

<div class="form-group">
  <%= label_tag(:content, "Content") %><br>
  <%= text_area_tag(:content, @post.content, class: 'form-control') %><br>
</div>

<div class="form-group">
  <%= submit_tag("Submit", class: "btn btn-primary") %>
</div>
<% end %>

app/views/posts/edit.html.erb
<%= render "post_header" %>
<h1>Edit Post</h1>

<%= render "shared/flash" %>

<%= form_for @post, url: {action: "update"}, html: {class: "form-group"} do |f| %>
    Title:      <%= f.text_field    :title,     { class: "form-control" }  %>
    Content:    <%= f.text_area     :content,   { class: "form-control" } %>
                <%= f.submit        "Submit",   { class: "btn btn-primary" } %>
<% end %>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>
<% @posts.each do |post| %>
<%= post.title %>
<%= post.content%>
<% end %>

<%= paginate @posts %>

app/views/posts/new.html.erb
<%= render "post_header" %>
<h1>New Post</h1>

<%= render "shared/flash" %>

<%= form_for @post, url: {action: "create"}, html: {class: "form-group"} do |f| %>
    Title:      <%= f.text_field    :title,     { class: "form-control" }  %>
    Content:    <%= f.text_area     :content,   { class: "form-control" } %>
                <%= f.submit        "Submit",   { class: "btn btn-primary" } %>
<% end %>

app/views/posts/show.html.erb
<%= provide(:page_header, @post.room.name) %>
<%= provide(:subtext, @post.room.description) %>
<%= provide(:room_link, room_path(@post.room) ) %>

<h3>&ldquo;<%= @post.content %>&rdquo;</h3>

<p class="text-left">
  <% if policy(@post).is_owner? %>

  <%= link_to "Edit Post", edit_post_path(:room_id => @post.room.id), class: "btn btn-default" %>
  <%= link_to "Delete Post", post_path(:room_id => @post.room.id), method: :delete, class: "btn btn-default" %>
  <% end %>
</p>

<%= render "shared/flash" %>

<div class="form-group">
  <%= form_tag(post_comments_path(@post.id), method: "post") do %>
    <%= hidden_field(:comment, :commentable_id, value: @post.id) %>
    <%= hidden_field(:comment, :commentable_type, value: 'Post') %>
    <%= label_tag(:comment, "Add a comment:") %>
    <%= text_area(:comment, :content, rows: 3, class: "form-control") %>
    <%= submit_tag("Submit", class: "btn btn-primary") %>
  <% end %>
</div>

<h2>Comments</h2>

<div class="container-fluid">

  <% if @comments.empty? %>

    <p>No replies yet.</p>

  <% else %>

     <%= render "shared/comments" %>

  <% end %>

</div>